[ 👁 ] ViewModels
NDecheva/FlightManager pull request #17
Opened 2024-12-18 09:32 UTC by KitaecaCapalot

This pull request introduces several new ViewModel classes to the `FlightManagerMVC` project, enhancing the application's ability to manage various aspects of flight and user data. The most important changes include the addition of ViewModels for booking, flight, and user management, as well as a base ViewModel class to streamline common properties.

New ViewModels added:

* [`AddBookingToFlightVM`](diffhunk://#diff-86ec7763f5e12dcce0698d46adbbd392fde9068f71f461cf76528a30115758d6R1-R11): A ViewModel for adding bookings to flights, including properties for flight and booking IDs and a list of bookings.

* [`BookingDetailsVM`](diffhunk://#diff-5b3dcada8e53d016dda65f1c5e495568b7dec73080bbea84626bf54ae7d22874R1-R28): A ViewModel for displaying booking details, including personal information, seat class, and associated flight details.

* [`BookingEditVM`](diffhunk://#diff-a77ebb7ad1ec05e3a49738d9de2383988349e2952553c235cb480f2c42d088aaR1-R42): A ViewModel for editing booking information, with validation attributes for required fields.

* [`FlightDetailsVM`](diffhunk://#diff-bdc9870b269ca8e31f281faf98efca51545ff8bde63c924d9b857346a9c29834R1-R28): A ViewModel for displaying flight details, including departure and arrival information, aircraft type, and associated bookings.

* [`FlightEditVM`](diffhunk://#diff-f808e8a48ae19cdaa4709acd5d3242fd03630156b261fe2931cd27f8e802988bR1-R48): A ViewModel for editing flight information, with validation attributes for required fields and a list of bookings.

* [`UserDetailsVM`](diffhunk://#diff-4bb383fd40ed85b35eee83ea258939667d385ca4a70b81e33791b5f1bd58ef4cR1-R18): A ViewModel for displaying user details, including personal information, user role, and associated bookings.

* [`UserEditVM`](diffhunk://#diff-7390b6d9a73b0e661b0027586fc325a291a2fc60ed5ca02e0fdc84c6d5fa1242R1-R43): A ViewModel for editing user information, with validation attributes for required fields and a list of bookings.

Base ViewModel:

* [`BaseVM`](diffhunk://#diff-75868388e4b753573e5fa770d79eced2f72a9baaea642a75203fab47ecc43f84R1-R13): A base ViewModel class containing a common `Id` property to be inherited by other ViewModels.

2024-12-18 13:55 UTC, Siyana05 approved these changes

2024-12-18 14:06 UTC, Siyana05 reviewed
Нещо не е наред. Намери си грешката.

2024-12-19 19:52 UTC, ectky requested changes

2024-12-19 19:52 UTC, ectky commented on FlightManager/FlightManagerMVC/ViewModels/FlightEditVM.cs
> +        public IEnumerable<SelectListItem> Bookings { get; set; }
🗑️

2024-12-19 20:21 UTC, KitaecaCapalot commented on FlightManager/FlightManagerMVC/ViewModels/FlightEditVM.cs
> +        public IEnumerable<SelectListItem> Bookings { get; set; }
Booking?

2024-12-19 20:33 UTC, ectky approved these changes

2024-12-19 20:34 UTC, merged