Entities and enums
NDecheva/FlightManager pull request #2
Opened 2024-11-20 07:27 UTC by Siyana05

2024-11-20 08:12 UTC, ectky requested changes

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Passenger.cs
> +    public class Passenger : BaseEntity
User

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Passenger.cs
> +        public int PassengerId { get; set; }
base entity няма ли такова свойство за Id вече?

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Passenger.cs
> +        public int PhoneNumber { get; set; }
номерата са стрингове

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Passenger.cs
> +        public int Password { get; set; }
ако паролата ми е: "парола1"?

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Passenger.cs
> +        public int PersonalId { get; set; }
това също трябва да е стринг

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Passenger.cs
> +        public bool Address { get; set; }
???

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Passenger.cs
> +        public bool Role { get; set; }
🤦

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManagerMVC/Enums/AircraftType.cs
> +﻿namespace FlightManagerMVC.Enums
В коя папка на кой проект се слагат енъмите?

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManagerMVC/Enums/Role.cs
> +﻿namespace FlightManagerMVC.Enums
В коя папка на кой проект се слагат енъмите?

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManagerMVC/Enums/SeatClass.cs
> +﻿namespace FlightManagerMVC.Enums
В коя папка на кой проект се слагат енъмите?

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public int FlightId { get; set; }
base entity няма ли такова свойство за Id вече?

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public bool DepartureLocation { get; set; }
🤦

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public bool ArrivalLocation { get; set; }
🤦

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public int DepartureTime { get; set; }
🤦

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public int ArrivalTime { get; set; }
🤦

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public bool AircraftType { get; set; }
🤦

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public int PersonalId { get; set; }
защо?

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public string PassengerCapacity { get; set; }
🤦

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public string BusinessClassCapacity { get; set; }
🤦

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public virtual List<Booking> Booking { get; set; }
Booking**S** -  лист е

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public int FlightId { get; set; }
къде е виртуалното свойство за този външен ключ?

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public int PersonalId { get; set; }
стринг

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public int PhoneNumber { get; set; }
стринг

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public int Password { get; set; }
ако паролата ми е: "парола1"?

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public bool Nationality { get; set; }
🤦

2024-11-20 08:12 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public bool SeatClass { get; set; }
🤦

2024-11-20 08:18 UTC, Siyana05 commented
И въъъ🤣🤣 мога да се защитя!!!

On Wed, 20 Nov 2024 at 10:13, Elitsa ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Passenger.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849799346>:
>
> > @@ -0,0 +1,24 @@
> +﻿using System;
> +using System.Collections.Generic;
> +using System.Linq;
> +using System.Text;
> +using System.Threading.Tasks;
> +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Passenger : BaseEntity
>
> User
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Passenger.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849799775>:
>
> > @@ -0,0 +1,24 @@
> +﻿using System;
> +using System.Collections.Generic;
> +using System.Linq;
> +using System.Text;
> +using System.Threading.Tasks;
> +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Passenger : BaseEntity
> +
> +    {
> +        public int PassengerId { get; set; }
>
> base entity няма ли такова свойство за Id вече?
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Passenger.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849800167>:
>
> > +using System.Collections.Generic;
> +using System.Linq;
> +using System.Text;
> +using System.Threading.Tasks;
> +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Passenger : BaseEntity
> +
> +    {
> +        public int PassengerId { get; set; }
> +        public string UserName { get; set; }
> +        public string FirstName { get; set; }
> +        public string LastName { get; set; }
> +        public string Email { get; set; }
> +        public int PhoneNumber { get; set; }
>
> номерата са стрингове
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Passenger.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849801163>:
>
> > +using System.Linq;
> +using System.Text;
> +using System.Threading.Tasks;
> +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Passenger : BaseEntity
> +
> +    {
> +        public int PassengerId { get; set; }
> +        public string UserName { get; set; }
> +        public string FirstName { get; set; }
> +        public string LastName { get; set; }
> +        public string Email { get; set; }
> +        public int PhoneNumber { get; set; }
> +        public int Password { get; set; }
>
> ако паролата ми е: "парола1"?
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Passenger.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849801661>:
>
> > +using System.Text;
> +using System.Threading.Tasks;
> +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Passenger : BaseEntity
> +
> +    {
> +        public int PassengerId { get; set; }
> +        public string UserName { get; set; }
> +        public string FirstName { get; set; }
> +        public string LastName { get; set; }
> +        public string Email { get; set; }
> +        public int PhoneNumber { get; set; }
> +        public int Password { get; set; }
> +        public int PersonalId { get; set; }
>
> това също трябва да е стринг
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Passenger.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849801822>:
>
> > +using System.Threading.Tasks;
> +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Passenger : BaseEntity
> +
> +    {
> +        public int PassengerId { get; set; }
> +        public string UserName { get; set; }
> +        public string FirstName { get; set; }
> +        public string LastName { get; set; }
> +        public string Email { get; set; }
> +        public int PhoneNumber { get; set; }
> +        public int Password { get; set; }
> +        public int PersonalId { get; set; }
> +        public bool Address { get; set; }
>
> ???
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Passenger.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849802089>:
>
> > +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Passenger : BaseEntity
> +
> +    {
> +        public int PassengerId { get; set; }
> +        public string UserName { get; set; }
> +        public string FirstName { get; set; }
> +        public string LastName { get; set; }
> +        public string Email { get; set; }
> +        public int PhoneNumber { get; set; }
> +        public int Password { get; set; }
> +        public int PersonalId { get; set; }
> +        public bool Address { get; set; }
> +        public bool Role { get; set; }
>
> 🤦
> ------------------------------
>
> In FlightManager/FlightManagerMVC/Enums/AircraftType.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849804408>:
>
> > @@ -0,0 +1,9 @@
> +﻿namespace FlightManagerMVC.Enums
>
> В коя папка на кой проект се слагат енъмите?
> ------------------------------
>
> In FlightManager/FlightManagerMVC/Enums/Role.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849804499>:
>
> > @@ -0,0 +1,8 @@
> +﻿namespace FlightManagerMVC.Enums
>
> В коя папка на кой проект се слагат енъмите?
> ------------------------------
>
> In FlightManager/FlightManagerMVC/Enums/SeatClass.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849804632>:
>
> > @@ -0,0 +1,8 @@
> +﻿namespace FlightManagerMVC.Enums
>
> В коя папка на кой проект се слагат енъмите?
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Flight.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849806643>:
>
> > +using System.Collections.Generic;
> +using System.Linq;
> +using System.Text;
> +using System.Threading.Tasks;
> +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Flight : BaseEntity
> +    {
> +
> +        public Flight()
> +        {
> +            this.Booking = new List<Booking>();
> +        }
> +
> +        public int FlightId { get; set; }
>
> base entity няма ли такова свойство за Id вече?
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Flight.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849807440>:
>
> > +using System.Linq;
> +using System.Text;
> +using System.Threading.Tasks;
> +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Flight : BaseEntity
> +    {
> +
> +        public Flight()
> +        {
> +            this.Booking = new List<Booking>();
> +        }
> +
> +        public int FlightId { get; set; }
> +        public bool DepartureLocation { get; set; }
>
> 🤦
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Flight.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849807500>:
>
> > +using System.Text;
> +using System.Threading.Tasks;
> +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Flight : BaseEntity
> +    {
> +
> +        public Flight()
> +        {
> +            this.Booking = new List<Booking>();
> +        }
> +
> +        public int FlightId { get; set; }
> +        public bool DepartureLocation { get; set; }
> +        public bool ArrivalLocation { get; set; }
>
> 🤦
> ------------------------------
>
> In FlightManager/FlightManager.Data/Entities/Flight.cs
> <https://github.com/NDecheva/FlightManager/pull/2#discussion_r1849807543>:
>
> > +using System.Threading.Tasks;
> +
> +namespace FlightManager.Data.Entities
> +{
> +    public class Flight : BaseEntity
> +    {
> +
> +        public Flight()
> +        {
> +            this.Booking = new List<Booking>();
> +        }
> +
> +        public int FlightId { get; set; }
> +        public bool DepartureLocation { get; set; }
> +        public bool ArrivalLocation { get; set; }
> +        public int DepartureTime { get; set; }
>
> 🤦
> ---- [...]

2024-11-21 19:10 UTC, ectky commented
@Nazdravec не може да ми резолвваш коментарите

2024-11-21 19:18 UTC, Nazdravec commented
@ectky huu biva li zadachata????

2024-11-21 19:40 UTC, ectky requested changes

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Passenger.cs
> +    public class Passenger : BaseEntity
нали имате user вече, махайте го този

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/User.cs
> +        public int PersonalId { get; set; }
ЕГН

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/User.cs
> +        public string Role { get; set; }
не е стринг

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public string DepartureTime { get; set; }
Departure**Time**

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public string ArrivalTime { get; set; }
Arrival**Time**

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public string AircraftType { get; set; }
не е стринг

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public int UserId {  get; set; }
къде пише че резервацията има връзка с потребител?

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public string SeatClass { get; set; }
не е стринг

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public string Password { get; set; }
къде пише че резервацията има парола?

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/FlightManagerDbContext.cs
> +                .HasOne(b => b.User)
къде пише че резервацията има потребител?

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/FlightManagerDbContext.cs
> +            modelBuilder.Entity<Flight>()
това вече е конфигурирано тук:
` modelBuilder.Entity<Booking>()
                .HasOne(b => b.Flight)
                .WithMany(f => f.Bookings)
                .HasForeignKey(b => b.FlightId)
                .OnDelete(DeleteBehavior.Restrict);`

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/FlightManagerDbContext.cs
> +            modelBuilder.Entity<User>()
къде пише че резервацията има потребител?

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/FlightManagerDbContext.cs
> +                    Password = "admin123",
хеш?

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/FlightManagerDbContext.cs
> +                    Role = "Admin"
неп

2024-11-21 19:40 UTC, ectky commented on FlightManager/FlightManager.Data/FlightManagerDbContext.cs
> +                    PersonalId = 1,
това не егн

2024-11-21 19:55 UTC, Nazdravec commented on FlightManager/FlightManager.Data/Entities/Passenger.cs
> +    public class Passenger : BaseEntity
при merge-a се наеба иначе го бяхме махнали

2024-11-21 19:55 UTC, Nazdravec commented on FlightManager/FlightManager.Data/Entities/User.cs
> +        public int PersonalId { get; set; }
public string PersonalId????

2024-11-21 19:57 UTC, Nazdravec commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public string DepartureTime { get; set; }
int depar ??

2024-11-21 19:58 UTC, Nazdravec commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public string ArrivalTime { get; set; }
dobre na vremenata s kakwo trqbwa da e

2024-11-21 19:58 UTC, Nazdravec commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public int UserId {  get; set; }
ne trqbwa li da ima vruzka

2024-11-21 19:59 UTC, Nazdravec commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public string SeatClass { get; set; }
koe ne trqbwa da e string

2024-11-21 19:59 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Passenger.cs
> +    public class Passenger : BaseEntity
добре че не е на shliokanica коментара 🙃

2024-11-21 20:00 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/User.cs
> +        public int PersonalId { get; set; }
ДА

2024-11-21 20:00 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public string DepartureTime { get; set; }
Departure**Time**

2024-11-21 20:05 UTC, Nazdravec commented on FlightManager/FlightManager.Data/Entities/Flight.cs
> +        public string DepartureTime { get; set; }
да ама какво трябва да е пред него

2024-11-21 20:12 UTC, Nazdravec commented on FlightManager/FlightManager.Data/FlightManagerDbContext.cs
> +                    Role = "Admin"
dobre de tuka osven egn kato string kakwo drugo ne e nared

2024-11-21 20:12 UTC, Nazdravec commented on FlightManager/FlightManager.Data/FlightManagerDbContext.cs
> +                    PersonalId = 1,
kakwo

2024-11-21 20:27 UTC, Nazdravec commented on FlightManager/FlightManager.Data/Entities/Booking.cs
> +        public string SeatClass { get; set; }
seatclass togava seatclassid da go naprawq i v enuma da go turq

2024-11-22 07:47 UTC, ectky requested changes

2024-11-22 07:47 UTC, ectky commented on FlightManager/FlightManager.Data/Entities/User.cs
> +        public int RoleId { get; set; }
ид за кое ентити е това?

2024-11-22 08:01 UTC, Nazdravec commented on FlightManager/FlightManager.Data/Entities/User.cs
> +        public int RoleId { get; set; }
добре госпожо не мога да разбера , да сложа ли роле ентити или да мъча нещо друго , в петшелтър и общия има роле ентити и е направено по този начин

2024-11-22 09:52 UTC, ectky requested changes

2024-11-22 09:52 UTC, ectky commented on FlightManager/FlightManager.Shared/Security/Contracts/IJwtSettings.cs
> +    public interface IJwtSettings
тези няма да ги ползваме

2024-11-22 09:52 UTC, ectky commented on FlightManager/FlightManager.Shared/Security/JwtSettings.cs
> +    public class JwtSettings : IJwtSettings
тези няма да ги ползваме

2024-11-23 18:34 UTC, ectky commented
Има 1 останал коментар по пул рекуеста.
This branch has conflicts that must be resolved

Можеш да резолвнеш конфликтите с:
git checkout main
git fetch
git pull
git checkout твоя-бранч
git rebase main

2024-11-23 19:59 UTC, ectky requested changes

2024-11-23 19:59 UTC, ectky commented on FlightManager/FlightManager.Shared/Enums/Role.cs
> +    public enum Role
този е ненужен

2024-11-25 15:33 UTC, ectky approved these changes

2024-11-25 16:41 UTC, merged