[ 🪐 ] DTOs
NDecheva/FlightManager pull request #4
Opened 2024-11-22 11:07 UTC by PetarBonev06

2024-11-23 18:31 UTC, ectky commented
This branch has conflicts that must be resolved

2024-11-23 18:33 UTC, ectky commented
> This branch has conflicts that must be resolved

git checkout main
git fetch
git pull
git checkout твоя-бранч
git rebase main

2024-11-26 12:25 UTC, Siyana05 commented on FlightManager/FlightManager.Data/Entities/User.cs
> -
Виж си редовете където е посочена грешката. Остави разстояние.

2024-11-26 12:25 UTC, Siyana05 commented on FlightManager/FlightManager.Data/Entities/User.cs
> -
За тук важи същото

2024-11-26 12:31 UTC, Siyana05 commented on FlightManager/FlightManager.Data/Entities/User.cs
> -
Остави разстояние.

2024-11-27 07:17 UTC, ectky requested changes

2024-11-27 07:17 UTC, ectky commented on FlightManager/FlightManager.Shared/Dtos/UserDto.cs
> +        public virtual List<BookingDto> Bookings { get; set; }
не е virtual

2024-11-27 07:17 UTC, ectky commented on FlightManager/FlightManager.Shared/Dtos/FlightDto.cs
> +        public virtual List<BookingDto> Bookings { get; set; }
не е virtual

2024-11-30 11:00 UTC, KitaecaCapalot approved these changes

2024-11-30 12:12 UTC, ectky approved these changes

2024-11-30 12:30 UTC, merged